name: sharebook_shell
description: "Sharebook - app shell para o site responsivo"
publish_to: 'none'
version: 2.0.1+20001

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.3
  image_picker: ^1.1.2
  webview_flutter_android: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuração do flutter_native_splash
# Rode: dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: false
